### ISSUE TITLE
Refactor code for null safety

### ISSUE THREAD

**Issue by kilikfan** [kilikfan/treasure#98]
https://flutter.dev/docs/null-safety has been introduced with Flutter V2, so would be good to refactor out project

**Comment by ghost** [comment]
This is kinda blocked because [flutter_swiper](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md) is basically dead and doesn't look like it'll update to null safety.

Probs worth waiting a bit to see what shakes out - maybe an official fork will emerge that supports it, or some other package will come along that solves the same problem :shrug:

**Comment by kilikfan** [comment]
There's an unofficial fork: [https://github.com/lianyagang/flutter_swiper_null_safety](https://github.com/lianyagang/flutter_swiper_null_safety)
```
import 'package:flutter_swiper_null_safety/flutter_swiper_null_safety.dart';
flutter_swiper_null_safety: ^1.0.1
```
I started looking into doing a big version bump and got a bit scared of breaking stuff especially with the null safety. If we do it then also note that the `audioplayers` package has updated and doesn't need an import of the `audiocache.dart` file any more as it has been refactored.
